/**
 * ExtractedData を client-env/ 配下の各ファイルに展開する writer 群。
 * intake-agent / discovery-agent から共通利用される。
 */
import { casePath, writeFile, repoRel, exists, readFile } from './io.js';
import { ExtractedData, ExtractedWbsRow } from './extract.js';

export interface WriteResult {
  path: string;
  bytes: number;
  action: 'created' | 'updated';
}

export interface WriteContext {
  clientSlug: string;
  generatedBy: string; // 例: "intake-agent" or "discovery-agent"
  force: boolean;
}

export function writeAllSections(data: ExtractedData, ctx: WriteContext): WriteResult[] {
  const results: WriteResult[] = [];
  results.push(writeCharter(data, ctx));
  results.push(...writeWbs(data, ctx));
  results.push(writeStakeholders(data, ctx));
  results.push(writeRisks(data, ctx));
  if (data.glossary.length > 0) results.push(writeGlossary(data, ctx));
  if (data.decisions.length > 0) results.push(writeDecisions(data, ctx));
  if (data.notes.length > 0) results.push(writeIntakeNotes(data, ctx));
  return results;
}

function writeOne(
  ctx: WriteContext,
  rel: string[],
  content: string,
): WriteResult {
  const path = casePath(ctx.clientSlug, ...rel);
  const action = exists(path) ? 'updated' : 'created';
  if (action === 'updated' && !ctx.force) {
    // 上書きしないが、新しい内容を _draft 接尾辞で並列保存
    const draftPath = path.replace(/\.md$/, '_draft.md').replace(/\.csv$/, '_draft.csv');
    writeFile(draftPath, content);
    return { path: draftPath, bytes: Buffer.byteLength(content), action: 'created' };
  }
  writeFile(path, content);
  return { path, bytes: Buffer.byteLength(content), action };
}

function footer(generatedBy: string): string {
  const now = new Date().toISOString().replace('T', ' ').slice(0, 16);
  return `\n\n---\nGenerated by: ${generatedBy} (AI PMO)\nLast updated: ${now}\nReviewed by: （要レビュー）\n`;
}

function writeCharter(data: ExtractedData, ctx: WriteContext): WriteResult {
  const c = data.charter;
  const body = [
    `# プロジェクト憲章`,
    '',
    '| 項目 | 内容 |',
    '|------|------|',
    `| プロジェクト ID | ${c.project_id || 'TBD'} |`,
    `| 契約金額 | ${c.contract_value || 'TBD'} |`,
    `| 期間 | ${c.period_start || 'TBD'} 〜 ${c.period_end || 'TBD'} |`,
    `| カットオーバー | ${c.cutover_date || 'TBD'} |`,
    '',
    '## 背景',
    '',
    c.background || '（要ヒアリング）',
    '',
    '## 目的',
    '',
    ...c.objectives.map((o, i) => `${i + 1}. ${o}`),
    '',
    '## スコープ（IN）',
    '',
    ...c.scope_in.map((s) => `- ${s}`),
    '',
    '## スコープ（OUT）',
    '',
    ...c.scope_out.map((s) => `- ${s}`),
    '',
    '## マイルストーン',
    '',
    '| # | マイルストーン | 計画日 | 状態 |',
    '|---|----------------|--------|------|',
    ...c.milestones.map(
      (m) =>
        `| ${m.id} | ${m.name} | ${m.date} | ${m.status === 'done' ? '完了' : m.status === 'in_progress' ? '進行中' : '計画中'} |`,
    ),
    '',
    '## 成功基準',
    '',
    '| # | 基準 | 測定方法 |',
    '|---|------|----------|',
    ...c.success_criteria.map((s) => `| ${s.id} | ${s.criterion} | ${s.measurement} |`),
    '',
    '## 想定リスク（憲章時点）',
    '',
    ...c.initial_risks.map((r) => `- ${r}`),
    '',
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['01-charter', 'project-charter.md'], body);
}

function writeWbs(data: ExtractedData, ctx: WriteContext): WriteResult[] {
  const rows = data.wbs;
  // CSV
  const csvHeader =
    'wbs_id,parent_id,name,owner,planned_start,planned_end,actual_start,actual_end,progress_pct,status,depends_on,backlog_id';
  const csvBody = rows.map((r) =>
    [
      r.wbs_id,
      r.parent_id ?? '',
      escapeCsv(r.name),
      r.owner ?? '',
      r.planned_start ?? '',
      r.planned_end ?? '',
      '',
      '',
      '0',
      'not_started',
      '',
      '',
    ].join(','),
  );
  const csv = [csvHeader, ...csvBody].join('\n') + '\n';

  // Markdown ビュー
  const md = [
    `# WBS`,
    '',
    `> 構造化データは [wbs.csv](./wbs.csv) を参照。本ファイルは Markdown ビュー。`,
    '',
    '## レベル別ブレークダウン',
    '',
    ...renderWbsTree(rows),
    '',
    footer(ctx.generatedBy),
  ].join('\n');

  return [
    writeOne(ctx, ['02-wbs', 'wbs.csv'], csv),
    writeOne(ctx, ['02-wbs', 'wbs.md'], md),
  ];
}

function renderWbsTree(rows: ExtractedWbsRow[]): string[] {
  const lines: string[] = [];
  const roots = rows.filter((r) => !r.parent_id);
  for (const root of roots) {
    lines.push(`### ${root.wbs_id} ${root.name} (担当: ${root.owner ?? '—'})`);
    for (const child of rows.filter((r) => r.parent_id === root.wbs_id)) {
      lines.push(`- ${child.wbs_id} ${child.name}${child.owner ? ` (${child.owner})` : ''}`);
      for (const grand of rows.filter((r) => r.parent_id === child.wbs_id)) {
        lines.push(`  - ${grand.wbs_id} ${grand.name}${grand.owner ? ` (${grand.owner})` : ''}`);
      }
    }
    lines.push('');
  }
  return lines;
}

function writeStakeholders(data: ExtractedData, ctx: WriteContext): WriteResult {
  const client = data.stakeholders.filter((s) => s.side === 'client');
  const vendor = data.stakeholders.filter((s) => s.side === 'vendor');
  const body = [
    `# ステークホルダー一覧`,
    '',
    '## クライアント側',
    '',
    '| 役割 | 氏名 | 所属 | 関与度 | 備考 |',
    '|------|------|------|--------|------|',
    ...client.map(
      (s) => `| ${s.role} | ${s.name ?? ''} | ${s.org ?? ''} | ${s.engagement ?? ''} | ${s.note ?? ''} |`,
    ),
    '',
    '## ベンダー側',
    '',
    '| 役割 | 氏名 | 所属 | 関与度 | 備考 |',
    '|------|------|------|--------|------|',
    ...vendor.map(
      (s) => `| ${s.role} | ${s.name ?? ''} | ${s.org ?? ''} | ${s.engagement ?? ''} | ${s.note ?? ''} |`,
    ),
    '',
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['00-context', 'stakeholders.md'], body);
}

function writeRisks(data: ExtractedData, ctx: WriteContext): WriteResult {
  const body = [
    `# リスク台帳`,
    '',
    '## リスク一覧',
    '',
    ...data.risks.flatMap((r) => [
      `### ${r.id} — ${r.title}`,
      '',
      '| 項目 | 内容 |',
      '|------|------|',
      `| 発生確率 | ${r.probability} |`,
      `| 影響 | ${r.impact} |`,
      `| トリガー | ${r.trigger} |`,
      `| 対応策 | ${r.countermeasure} |`,
      `| エスカレーション先 | ${r.escalation ?? ''} |`,
      '',
    ]),
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['06-risks', 'risk-register.md'], body);
}

function writeGlossary(data: ExtractedData, ctx: WriteContext): WriteResult {
  const existingPath = casePath(ctx.clientSlug, '00-context', 'glossary.md');
  const existingHeader = exists(existingPath)
    ? readFile(existingPath).split('\n').slice(0, 4).join('\n') + '\n'
    : '# 用語集\n\nPJ 内で頻出する略語・固有用語の定義。\n\n';
  const body = [
    existingHeader,
    '| 用語 | 正式名称 / 意味 |',
    '|------|----------------|',
    ...data.glossary.map((g) => `| ${g.term} | ${g.definition} |`),
    '',
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['00-context', 'glossary.md'], body);
}

function writeDecisions(data: ExtractedData, ctx: WriteContext): WriteResult {
  const body = [
    `# 意思決定ログ`,
    '',
    '| ID | 日付 | 決定事項 | 決定者 | 文脈・背景 |',
    '|----|------|----------|--------|------------|',
    ...data.decisions.map(
      (d) => `| ${d.id} | ${d.date} | ${d.decision} | ${d.decider} | ${d.context} |`,
    ),
    '',
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['08-decisions', 'decision-log.md'], body);
}

function writeIntakeNotes(data: ExtractedData, ctx: WriteContext): WriteResult {
  const body = [
    `# AI 抽出 ノート — 要ヒアリング項目`,
    '',
    `${ctx.generatedBy} が入力資料から構造化を行った際に、不確実だった点・補完が必要だった点をまとめたものです。`,
    '人間レビュー時にこのリストを潰してください。',
    '',
    ...data.notes.map((n, i) => `${i + 1}. ${n}`),
    '',
    footer(ctx.generatedBy),
  ].join('\n');
  return writeOne(ctx, ['00-context', 'intake-notes.md'], body);
}

function escapeCsv(v: string): string {
  if (v.includes(',') || v.includes('"') || v.includes('\n')) {
    return `"${v.replace(/"/g, '""')}"`;
  }
  return v;
}

export function summarizeResults(results: WriteResult[], destRoot: string): string {
  return results
    .map((r) => `  ✓ ${r.action === 'created' ? '作成' : '上書'} ${repoRel(r.path)} (${(r.bytes / 1024).toFixed(1)} KB)`)
    .join('\n');
}
