const dailyRoutine = [
  { time: '朝一 5分', task: 'ビューワーのダッシュボードを開く（KPI / High 課題 / 重点リスク確認）', who: 'PM / PMO' },
  { time: '朝一 3分', task: 'Slack #ai-pmo-alerts で前夜の検知結果を確認', who: 'PMO' },
  { time: '朝一 2分', task: '当日の会議予定・Zoom 録音 ON 設定確認', who: 'PM' },
  { time: '会議中', task: '「決定」「やる」「期限」など意識的に発声、機密は「記録外」と前置き', who: '全員' },
  { time: '会議後 1h', task: 'scribe-agent が議事録生成 → 10分レビュー → Reviewed by 記入', who: 'サブ PM' },
  { time: '夕方', task: 'triager-agent が課題リスコア、High 件数を確認', who: 'PM' },
];

const weeklyRoutine = [
  { day: '月 06:00', task: 'reporter-agent が週次レポート自動生成、Slack 通知', who: 'AI' },
  { day: '月 09:00', task: 'PMO 担当が 30 分で報告書レビュー', who: 'PMO 担当' },
  { day: '月 10:00', task: '週次定例で AI PMO 進捗を冒頭 5 分確認', who: '全員' },
  { day: '月 11:00', task: 'PM 承認 → 経営層へ Slack DM / メール / Confluence へ配信', who: 'PM' },
  { day: '金 17:00', task: 'watcher-agent がリスク台帳再評価', who: 'AI' },
];

const monthlyRoutine = [
  { phase: '月初 第1営業日 06:00', task: 'reporter-agent が月次経営報告自動生成', who: 'AI' },
  { phase: '月初 第2営業日 60分', task: 'PMO 室長 + PM レビュー会、数値解釈とエグゼクティブメッセージ磨き', who: 'PMO 室長 + PM' },
  { phase: '月初 第2営業日', task: 'ビューワーから PDF 出力 → 経営報告会で発表', who: 'PMO 室長 + Sr. コンサル' },
  { phase: '月末', task: 'KPI 集計 → Sr. コンサルとの 60 分振り返り', who: 'PMO 室長 + Sr. コンサル' },
];

const successMetrics = [
  '月次経営会議で AI PMO 生成資料がデフォルトで使われている',
  'PMO ジュニアでも週次レポートを 30 分以内に確認・承認できる',
  '課題管理表に常時 30 件以上のアクティブ案件があり、滞留がない',
  '議事録の確定リードタイムが平均 4 時間以内',
  'AI 生成物への修正率が 30% 以下',
  'PM 満足度が 4.0/5.0 以上',
];

const faqs = [
  {
    q: 'AI が間違ったらどうする？',
    a: '最終責任は PM/PMO にあり、AI 生成物は全て人間レビューを通る前提。ただし全件チェックでは AI 化の意味が薄れるため、議事録は全件 / 週次レポートは全件 / 課題自動起票はスポットチェック、というふうにメリハリをつける。',
  },
  {
    q: 'クライアントに AI 利用を伝えるべき？',
    a: '伝える前提。契約書・キックオフ資料で明示し、AI 生成物には `Generated by:` フッターを必ず付ける。透明性が信頼を生む。',
  },
  {
    q: 'データ漏えいリスクは？',
    a: 'API キーは Doppler / 1Password で集中管理（90日ローテ）、リポは Private、センシティブ情報は PII 検知でマスク。詳細は docs/enterprise-considerations.md。',
  },
  {
    q: 'AI 利用料が膨らんだら？',
    a: '月次でモニタ。Opus → Haiku 切替で 80% 削減（精度は下がる）。一部生成物は週次→月次に頻度ダウンで対応。',
  },
  {
    q: '外部 API NG の IT 統制と言われた',
    a: 'AWS Bedrock 経由で Claude を呼んで VPC 内完結、Doppler を社内 Vault に置換、Render の代わりに AWS ECS/EC2 へデプロイ。オンプレ運用は追加 ¥3〜5M/年。',
  },
];

export default function Operations() {
  return (
    <div className="space-y-8">
      <section>
        <div className="text-xs uppercase tracking-wide text-brand-700 font-semibold">Operations Guide</div>
        <h1 className="text-2xl font-bold mt-1">運営の使い方（PM / PMO 担当向け）</h1>
        <p className="text-sm text-slate-600 mt-2 max-w-3xl">
          Phase 5 運用フェーズに入った PJ で、PM / PMO 担当者がどう AI PMO を日常業務に組み込むかの具体手順。
          日次 / 週次 / 月次のカデンスとイレギュラー対応をカバー。
        </p>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">🌅 朝一でやること（毎営業日、5〜10 分）</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-xs uppercase text-slate-500">
              <tr>
                <th className="text-left px-3 py-2 font-semibold w-28">タイミング</th>
                <th className="text-left px-3 py-2 font-semibold">アクション</th>
                <th className="text-left px-3 py-2 font-semibold w-32">担当</th>
              </tr>
            </thead>
            <tbody>
              {dailyRoutine.map((r, i) => (
                <tr key={i} className="border-t border-slate-100">
                  <td className="px-3 py-2 font-mono text-xs text-brand-700">{r.time}</td>
                  <td className="px-3 py-2">{r.task}</td>
                  <td className="px-3 py-2 text-xs text-slate-600">{r.who}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">📅 週次ルーチン</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-xs uppercase text-slate-500">
              <tr>
                <th className="text-left px-3 py-2 font-semibold w-28">タイミング</th>
                <th className="text-left px-3 py-2 font-semibold">アクション</th>
                <th className="text-left px-3 py-2 font-semibold w-32">担当</th>
              </tr>
            </thead>
            <tbody>
              {weeklyRoutine.map((r, i) => (
                <tr key={i} className="border-t border-slate-100">
                  <td className="px-3 py-2 font-mono text-xs text-brand-700">{r.day}</td>
                  <td className="px-3 py-2">{r.task}</td>
                  <td className="px-3 py-2 text-xs text-slate-600">{r.who}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">📊 月次ルーチン（経営報告含む）</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-xs uppercase text-slate-500">
              <tr>
                <th className="text-left px-3 py-2 font-semibold w-44">タイミング</th>
                <th className="text-left px-3 py-2 font-semibold">アクション</th>
                <th className="text-left px-3 py-2 font-semibold w-36">担当</th>
              </tr>
            </thead>
            <tbody>
              {monthlyRoutine.map((r, i) => (
                <tr key={i} className="border-t border-slate-100">
                  <td className="px-3 py-2 font-mono text-xs text-brand-700">{r.phase}</td>
                  <td className="px-3 py-2">{r.task}</td>
                  <td className="px-3 py-2 text-xs text-slate-600">{r.who}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">🎯 「使いこなしている」状態の指標</h2>
        <p className="text-sm text-slate-600 mb-3">
          3 ヶ月運用後にこの 6 つのうち <strong>4 つ以上達成</strong>なら Phase 2（拡大）へ移行判定。
        </p>
        <ul className="space-y-2">
          {successMetrics.map((m, i) => (
            <li key={i} className="flex items-start gap-2 text-sm">
              <span className="text-emerald-600 mt-0.5">✓</span>
              <span>{m}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">📤 ビューワーから出力できるもの</h2>
        <div className="grid md:grid-cols-2 gap-3">
          <div className="border border-slate-200 rounded-lg p-4">
            <div className="font-semibold mb-1">📊 Excel 出力</div>
            <ul className="text-sm text-slate-600 space-y-1 mt-2">
              <li>• WBS（階層インデント・進捗率・色分け）</li>
              <li>• 課題管理表（優先度色分け + 集計シート）</li>
              <li>• リスク台帳（スコア色分け）</li>
            </ul>
            <div className="text-xs text-slate-500 mt-2">各ページの「📊 Excel」ボタンから即 DL</div>
          </div>
          <div className="border border-slate-200 rounded-lg p-4">
            <div className="font-semibold mb-1">🖨 PDF 出力</div>
            <ul className="text-sm text-slate-600 space-y-1 mt-2">
              <li>• 週次・月次報告書</li>
              <li>• 議事録</li>
              <li>• プロジェクト憲章 / ステークホルダー / 用語集</li>
            </ul>
            <div className="text-xs text-slate-500 mt-2">「🖨 印刷/PDF」ボタン → ブラウザの「PDF として保存」</div>
          </div>
        </div>
      </section>

      <section className="card p-5">
        <h2 className="font-bold text-lg mb-3">❓ よくある質問</h2>
        <div className="space-y-4">
          {faqs.map((f, i) => (
            <details key={i} className="border-b border-slate-100 pb-3 last:border-0">
              <summary className="cursor-pointer font-medium text-slate-800 hover:text-brand-700">
                {f.q}
              </summary>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="card p-5 bg-gradient-to-br from-brand-50 to-white">
        <h2 className="font-bold text-lg mb-2">📖 詳細プレイブック</h2>
        <p className="text-sm text-slate-700">
          全工程・全フェーズの詳細：{' '}
          <a
            href="https://github.com/keitaurano-del/ai-pmo/tree/main/docs/deployment-playbook"
            target="_blank"
            rel="noreferrer"
            className="text-brand-600 hover:underline font-medium"
          >
            docs/deployment-playbook/ on GitHub
          </a>
        </p>
      </section>
    </div>
  );
}
