import { complete } from './lib/client.js';
import { casePath, exists, listFiles, readAgentPrompt, readFile, readMany, repoRel, writeFile } from './lib/io.js';
import { Agent, AgentRunOpts, AgentResult } from './types.js';

/**
 * reporter-agent: WBS / 課題 / リスク / 直近議事録 を集約し週次報告書を生成。
 *
 * 入力: なし（case のファイル群を自動収集）
 * 出力: case-studies/<client>/client-env/07-reports/<YYYY-Wnn>_weekly-report.md
 */
export const reporter: Agent = {
  name: 'reporter',
  description: '週次進捗報告書を WBS / 課題 / リスク / 議事録から自動生成',
  async run(opts: AgentRunOpts): Promise<AgentResult> {
    const agentPrompt = readAgentPrompt('reporter');
    const ctx = collectContext(opts.clientSlug);

    const system = `${agentPrompt}\n\n以下のコンテキストを使い、週次進捗報告書を Markdown で生成すること。出力は Markdown のみ、説明文不要。`;

    const user = [
      '## プロジェクト憲章',
      ctx.charter || '（憲章未作成）',
      '',
      '## WBS (CSV)',
      ctx.wbsCsv || '（WBS なし）',
      '',
      '## 課題 (CSV)',
      ctx.issuesCsv || '（課題なし）',
      '',
      '## リスク台帳',
      ctx.risks || '（リスク台帳なし）',
      '',
      '## 直近の議事録 (最新 2 件)',
      ctx.recentMeetings.length > 0 ? ctx.recentMeetings.join('\n\n---\n\n') : '（議事録なし）',
      '',
      '## 指示',
      '上記コンテキストから「週次進捗報告書」を生成してください。',
      'テンプレートに従い、エグゼクティブサマリ（3行）、全体進捗テーブル、マイルストーン状況、',
      '今週の達成、進行中の作業、重要トピック、来週の予定、AI PMO 内部メトリクスを含めること。',
      'ファイル末尾に `Generated by: reporter-agent (AI PMO)` フッターを必ず付ける。',
    ].join('\n');

    const weekTag = isoWeekTag(new Date());
    const outputPath = casePath(opts.clientSlug, '07-reports', `${weekTag}_weekly-report.md`);

    if (opts.dryRun) {
      return {
        outputs: [{ path: outputPath, bytes: 0 }],
        promptPreview: `[SYSTEM]\n${system.slice(0, 200)}...\n\n[USER 先頭]\n${user.slice(0, 800)}...`,
        notes: [
          'dry-run: Claude API は呼ばれていません。',
          `収集したコンテキスト: charter=${!!ctx.charter}, wbs=${!!ctx.wbsCsv}, issues=${!!ctx.issuesCsv}, risks=${!!ctx.risks}, meetings=${ctx.recentMeetings.length}件`,
          `出力先 (予定): ${repoRel(outputPath)}`,
        ],
      };
    }

    const result = await complete({ system, user, model: 'opus', maxTokens: 6000 });
    writeFile(outputPath, result.text);
    return {
      outputs: [{ path: outputPath, bytes: Buffer.byteLength(result.text), preview: result.text.slice(0, 300) }],
      promptPreview: `[SYSTEM]\n${system.slice(0, 200)}...`,
      usage: result.usage,
    };
  },
};

function collectContext(slug: string) {
  const charterPath = casePath(slug, '01-charter', 'project-charter.md');
  const wbsCsvPath = casePath(slug, '02-wbs', 'wbs.csv');
  const issuesCsvPath = casePath(slug, '05-issues', 'issues.csv');
  const risksPath = casePath(slug, '06-risks', 'risk-register.md');
  const meetingDir = casePath(slug, '04-meetings');

  const meetingFiles = listFiles(meetingDir, /\.md$/).reverse().slice(0, 2); // 新しい順 2 件

  return {
    charter: exists(charterPath) ? readFile(charterPath) : '',
    wbsCsv: exists(wbsCsvPath) ? readFile(wbsCsvPath) : '',
    issuesCsv: exists(issuesCsvPath) ? readFile(issuesCsvPath) : '',
    risks: exists(risksPath) ? readFile(risksPath) : '',
    recentMeetings: readMany(meetingFiles).map((m) => m.body),
  };
}

function isoWeekTag(d: Date): string {
  // ISO week (Mon=start). e.g. 2026-W20
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const dayNum = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((+date - +yearStart) / 86400000 + 1) / 7);
  return `${date.getUTCFullYear()}-W${String(week).padStart(2, '0')}`;
}
