import { complete } from './lib/client.js';
import { casePath, exists, readAgentPrompt, readFile, repoRel, writeFile } from './lib/io.js';
import { Agent, AgentRunOpts, AgentResult } from './types.js';

/**
 * scribe-agent: 会議の transcript (txt or md) を読み、議事録 Markdown を生成。
 *
 * 入力: --input <path>   transcript（プレーンテキスト）
 *       --input が省略された場合、example transcript を内蔵で使う（デモ用）。
 * 出力: case-studies/<client>/client-env/04-meetings/YYYY-MM-DD_<derived>.md
 */
export const scribe: Agent = {
  name: 'scribe',
  description: '会議の transcript から議事録 Markdown を生成',
  async run(opts: AgentRunOpts): Promise<AgentResult> {
    const transcript = loadTranscript(opts);

    const agentPrompt = readAgentPrompt('scribe');
    const glossaryPath = casePath(opts.clientSlug, '00-context', 'glossary.md');
    const glossary = exists(glossaryPath) ? readFile(glossaryPath) : '（用語集なし）';
    const stakeholdersPath = casePath(opts.clientSlug, '00-context', 'stakeholders.md');
    const stakeholders = exists(stakeholdersPath) ? readFile(stakeholdersPath) : '（ステークホルダー定義なし）';

    const system = `${agentPrompt}\n\n以下のコンテキストを参照しながら議事録を生成すること。出力は Markdown のみ、説明文不要。`;

    const user = [
      '## 用語集 (glossary.md)',
      glossary,
      '',
      '## ステークホルダー (stakeholders.md)',
      stakeholders,
      '',
      '## 会議 transcript',
      transcript,
      '',
      '## 指示',
      '上記 transcript から議事録 Markdown を生成してください。',
      'テンプレートに従い、議論サマリ・決定事項・ToDo を抽出。',
      'ファイル末尾に `Generated by: scribe-agent (AI PMO)` フッターを必ず付ける。',
    ].join('\n');

    const today = new Date().toISOString().slice(0, 10);
    const outputPath = casePath(opts.clientSlug, '04-meetings', `${today}_generated.md`);

    if (opts.dryRun) {
      return {
        outputs: [{ path: outputPath, bytes: 0 }],
        promptPreview: `[SYSTEM]\n${system.slice(0, 200)}...\n\n[USER]\n${user.slice(0, 500)}...`,
        notes: [
          'dry-run: Claude API は呼ばれていません。',
          `入力 transcript: ${opts.inputFile ?? '(内蔵サンプル)'}`,
          `出力先 (予定): ${repoRel(outputPath)}`,
        ],
      };
    }

    const result = await complete({ system, user, model: 'opus', maxTokens: 4096 });
    writeFile(outputPath, result.text);
    return {
      outputs: [{ path: outputPath, bytes: Buffer.byteLength(result.text), preview: result.text.slice(0, 300) }],
      promptPreview: `[SYSTEM]\n${system.slice(0, 200)}...`,
      usage: result.usage,
    };
  },
};

function loadTranscript(opts: AgentRunOpts): string {
  if (opts.inputFile && exists(opts.inputFile)) {
    return readFile(opts.inputFile);
  }
  return SAMPLE_TRANSCRIPT;
}

const SAMPLE_TRANSCRIPT = `[10:00:05] 岡本 PM: おはようございます。週次定例始めます。アジェンダは進捗確認・課題レビュー・来週の予定。
[10:01:12] 立花 サブPM: 先週の達成は販促系業務ヒアリング完了と可用性要件の確定です。
[10:02:30] 真壁 アーキ: ただ販促系の要件定義書レビューが M-Mart 西野部長から返ってきていなくて 3 日延伸しています。
[10:03:45] 岡本 PM: それは ISS-024 ですね。優先度を High に上げて、西野部長と再調整します。5/16 までに完了させたい。
[10:04:50] 真壁 アーキ: それからセキュリティ要件、情シスとの方針が固まっていないので 5/14 にすり合わせ会を入れます。
[10:06:10] 岡本 PM: いいですね。じゃあ決定として、販促系レビューは岡本が再調整、セキュリティ要件会は真壁が 5/14 にセット、で。
[10:07:30] 久野 PMO: AI PMO 中間レビュー資料のドラフトを私が手配します。5/20 までに出します。
[10:08:50] 岡本 PM: 来週は 5/13 Backlog データクリーニング第2回、5/14 セキュリティ会、5/16 販促系レビューのデッドライン。5/18 が次回定例です。
[10:10:00] 全員: 了解です。
[10:10:30] 岡本 PM: では今日はこれで終わります、ありがとうございました。`;
